# Ensure that your "data_dir" contains the following items:
#
# data_dir
#   - covid_train.csv
#   - covid_test.csv

data:
  data_dir: "data/ml2023spring-hw1"
  seed: 8590  # Your seed number, you can pick your lucky number. :)
  valid_ratio: 0.1  # valid_size = train_size * valid_ratio

model:
  num_layers: 4
  hidden_size: 64

training:
  batch_size: 128
  max_epochs: 1000
  weight_decay: 0.0001
  learning_rate: 0.001
  early_stopping: 300  # If models has not improved for this many consecutive epochs, stop training.
  output_dir: "output"
