# Ensure that your "data_dir" contains the following items:
#
# data_dir/
#   - mapping.json
#   - metadata.json
#   - testdata.json
#   - *.pt
data:
  data_dir: "data/ml2023spring-hw4"
  valid_ratio: 0.1
  segment_len: 128
  seed: 8590 # Your seed number, you can pick your lucky number. :)

model:
  d_model: 80 # Project the dimension of features from that of input into d_model.

training:
  batch_size: 64
  learning_rate: 0.001
  dropout: 0.1
  weight_decay: 0.0001
  max_steps: 70000
  validation_after_n_steps: 2000
  save_best_freq: 10000
  warmup_steps: 1000
  output_dir: "output"
