data:
  data_dir: "./data"
  seed: 8590  # Your seed number, you can pick your lucky number. :)
  valid_ratio: 0.1  # validation_size = train_size * valid_ratio

model:
  hidden_layers: 3
  hidden_size: 64

training:
  batch_size: 256
  epochs: 3000
  learning_rate: 0.001
  optimizer: "adam"  # adam or sgd
  weight_decay: 0.0001
  criterion: "mse"  # mse or cross_entropy
  early_stop: 600  # If models has not improved for this many consecutive epochs, stop training.
  output_dir: "./output"
