data:
  data_dir: "./data"
  seed: 8590  # Your seed number, you can pick your lucky number. :)
  valid_ratio: 0.1  # validation_size = train_size * valid_ratio
  concat_nframes: 19  # Totals frame after concat past and future features, n must be odd (total 2k + 1 = n frames).

model:
  lstm_num_layers: 3
  lstm_hidden_size: 256
  mlp_hidden_layers: 1
  mlp_hidden_size: 128

training:
  batch_size: 512
  num_epochs: 15
  learning_rate: 0.001
  optimizer: "AdamW"  # Adam or SGD or AdamW
  weight_decay: 0.0001
  dropout: 0.5
  criterion: "cross_entropy"  # mse or cross_entropy
  early_stop: 3  # If models has not improved for this many consecutive epochs, stop training.
  output_dir: "./output"